# ====== 基本服务器信息 ======
server_name = SL-Minetest-Spot-on-Server
server_description = Powered by AWS EKS and Spot Instances
# 暂时不向全球公共服务器列表广播，作为私服运行
server_announce = false 

# ====== 游戏玩法设定 ======
max_users = 15
creative_mode = false
enable_damage = true

# ====== 网络与性能设定 ======
# 必须监听 0.0.0.0，否则 Docker/K8s 外部无法访问
bind_address = 0.0.0.0
port = 30000